#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
!pip install numpy

In [1]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [3]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [4]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
arr3=np.arange(0,10,1) ## np.arange(start, stop, step)
print(arr3)
print(type(arr3))
print(arr3.shape)
np.arange(0,10,2).reshape(5,1)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
''' 
| Code                      | Shape   | Meaning                                                     |
| ------------------------- | ------- | ----------------------------------------------------------- |
| `np.array([1,2,3])`       | `(3,)`  | 1D array                                                    |
| `np.array([[1,2,3]])`     | `(1,3)` | 1 row, 3 columns                                            |
| `np.array([[1],[2],[3]])` | `(3,1)` | 3 rows, 1 column                                            |
| `np.arange(0,10)`         | `(10,)` | Numbers 0–9                                                 |
| `.reshape(r,c)`           | `(r,c)` | Convert array shape without changing the number of elements |

np.array()
np.arange()
shape
reshape()
Difference between 1D, row vector (1,n), and column vector (n,1), as these are asked very frequently.


'''

In [ ]:
np.ones((3,4)) ##NumPy's default datatype is float.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
''' 
| Attribute      | Output               | Meaning                               |
| -------------- | -------------------- | ------------------------------------- |
| `arr.shape`    | `(2,3)`              | 2 rows, 3 columns                     |
| `arr.ndim`     | `2`                  | Number of dimensions                  |
| `arr.size`     | `6`                  | Total number of elements              |
| `arr.dtype`    | `int64` (or `int32`) | Data type of each element             |
| `arr.itemsize` | `8` (or `4`)         | Bytes occupied by one element         |
| `arr.nbytes`   | `48`                 | Total memory used (`size × itemsize`) |

Short Notes (Python DA)
np.ones((r,c)) → Creates an r × c array filled with 1's.
np.eye(n) → Creates an n × n identity matrix (1's on the diagonal, 0's elsewhere).
shape → Size of each dimension (rows, columns, ...).
ndim → Number of dimensions (axes).
size → Total number of elements.
dtype → Data type of the array elements.
itemsize → Memory used by one element (in bytes).
nbytes → Total memory used = size × itemsize.


'''

In [15]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)  ##Runs optimized C code internally (much faster).
##That's why NumPy is preferred for data analysis

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [23]:
## Universal Function
##Universal Functions (ufuncs)
##A Universal Function (ufunc) is simply a NumPy function that performs an operation element-wise on arrays.
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))
print(np.sin(np.pi/2))
## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
1.0
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(arr[1:,1:3]) ##1st row to end row and 1st col to 2nd col (considering 0th row and 0th column)

[[ 6  7]
 [10 11]]


In [ ]:
'''
Slicing:

arr[0:2, 1:3]
Rows: 0 and 1
Columns: 1 and 2

'''

In [ ]:
'''  
Vectorized Operations
+, -, *, / on NumPy arrays are element-wise.
Vectorization removes the need for explicit Python loops and is much faster.
Universal Functions (ufuncs)
np.sqrt(arr) → Square root of each element.
np.exp(arr) → Computes e
x
 for each element.
np.sin(arr) → Sine of each element (input in radians).
np.log(arr) → Natural logarithm (base e).
Indexing & Slicing
arr[row, col] → Single element.
arr[row] → Entire row.
arr[:, col] → Entire column.
arr[r1:r2, c1:c2] → Slice rows and columns (end index excluded).

These topics—especially vectorization, np.sqrt, np.log, and 2D indexing—are among the most common NumPy concepts asked in Data Analyst interviews.

'''

In [26]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [28]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [29]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [30]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)
''' 
Since the array has 10 elements (even)
1 2 3 4 5 6 7 8 9 10
Middle two values
5 and 6
Median
(5+6)/2
=5.5

odd number of elements
np.median([1,2,3,4,5])
Middle value
3
'''

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
''' 
| Function      | Purpose                                 |
| ------------- | --------------------------------------- |
| `np.mean()`   | Average of values                       |
| `np.median()` | Middle value after sorting              |
| `np.std()`    | Measures spread of data around the mean |
| `np.var()`    | Variance = `(std)^2`                    |

Mean vs Median
Mean → affected by outliers.
Median → robust to outliers.
Standardization (often casually called normalization)
normalized = (data - np.mean(data)) / np.std(data)

Properties:

Mean becomes 0.
Standard deviation becomes 1.

Interview Note: Strictly speaking, the formula (x - mean) / std is called Standardization or Z-score Normalization. Another technique called Min-Max Normalization uses:

(x - min) / (max - min)

Many courses use the word "normalization" loosely, but in interviews it's good to know the distinction.


'''

In [32]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [ ]:
''' 
Boolean Indexing: Filter array elements using conditions.
data[data > 5] → Values greater than 5.
& → AND (both conditions must be true).
| → OR (either condition can be be true).
~ → NOT (invert the condition).

Always write:
(condition1) & (condition2)

not
condition1 & condition2
Never use and or or with NumPy arrays; use & and | instead.

This is one of the most frequently used NumPy features because it's the foundation of filtering data in both NumPy and Pandas.


'''

In [ ]:
''' 
arr = np.array([2,4,6,8])

np.sum(arr)      # 20
np.max(arr)      # 8
np.min(arr)      # 2
np.argmax(arr)   # 3
np.argmin(arr)   # 0


1. Axis Parameter ⭐⭐⭐⭐⭐
Meaning
axis tells NumPy along which axis to perform the operation.
For a 2D array:
arr = np.array([[1,2,3],
                [4,5,6]])
        Columns
        ↓ axis=0
     1  2  3
     4  5  6
     → axis=1 (Rows)
axis=0 → Column-wise (↓)
np.sum(arr, axis=0)
1+4 = 5
2+5 = 7
3+6 = 9
Output
array([5, 7, 9])


axis=1 → Row-wise (→)
np.sum(arr, axis=1)
1+2+3 = 6
4+5+6 = 15
Output
array([6, 15])

Works with many functions
np.sum(arr, axis=0)
np.mean(arr, axis=1)
np.max(arr, axis=0)
np.min(arr, axis=1)
np.std(arr, axis=0)
🎯 Easy Trick to Remember
axis=0 → ↓ Down columns

axis=1 → → Across rows

or

axis=0 = Vertical

axis=1 = Horizontal
Interview Question

Q. Difference between axis=0 and axis=1?

Answer:

axis=0 → Operation is performed column-wise.
axis=1 → Operation is performed row-wise.
2. NumPy Random Module ⭐⭐⭐⭐

Used to generate random numbers, useful for testing, simulations, and ML.

np.random.rand()

Generates random decimal numbers between 0 and 1.

np.random.rand()
Example
0.6482
2×3 matrix
np.random.rand(2,3)

np.random.randint()
Generates random integers.
np.random.randint(1,10)
Output
7

Random 2×3 array
np.random.randint(1,10,(2,3))

Example
[[3 8 2]
 [9 1 5]]

Note: The upper limit is exclusive.

np.random.randint(1,10)
Generates numbers from 1 to 9, not 10.
np.random.randn()
Generates numbers from the standard normal distribution.
np.random.randn(3)
Example
[-0.52  1.34 -0.11]

Properties

Mean ≈ 0
Standard deviation ≈ 1

Mostly used in Machine Learning and Statistics.

np.random.seed()

Makes random numbers repeatable.

np.random.seed(42)

print(np.random.randint(1,10,5))

Output every time

[7 4 8 5 7]

Without seed()

[3 8 1 5 2]

Next run

[6 2 9 4 1]

Every execution gives different values.

With seed(42), the output stays the same every time, which helps in debugging and reproducibility.

📌 Interview Cheat Sheet
Function	Purpose
axis=0	Column-wise operation
axis=1	Row-wise operation
np.random.rand()	Random floats in [0,1)
np.random.randint(a,b)	Random integers in [a,b)
np.random.randn()	Random numbers from standard normal distribution
np.random.seed()	Makes random output reproducible
⭐ One-line Memory Trick
Axis
axis=0 → Columns (↓)
axis=1 → Rows (→)
Random
rand() → Random decimal (0–1)
randint() → Random integer
randn() → Normal distribution
seed() → Same random numbers every run
'''